### @POST: Create new request
POST http://localhost:8080/request
Content-Type: application/json

{
  "customerId": 1000,
  "menuItems": [
    {
      "menuId": 1000,
      "quantity": 2
    }
  ]
}

### @GET: Fetch given request
GET http://localhost:8080/request/1001
Content-Type: application/json

### @GET: Fetch menu items
GET http://localhost:8080/request/menu-items
Content-Type: application/json

### @GET: notification status
GET http://localhost:8080/request/notification/status
Content-Type: text/event-stream